[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zkroute = "9fhQBbumKEFuXtMBDw8AaQyAjCorLGJQiS3skWZdQyQD"

[programs.devnet]
zkroute = "9fhQBbumKEFuXtMBDw8AaQyAjCorLGJQiS3skWZdQyQD"

[programs.mainnet]
zkroute = "9fhQBbumKEFuXtMBDw8AaQyAjCorLGJQiS3skWZdQyQD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[package]
name = "zkroute"
version = "0.1.0"
description = "ZKRoute program"
repository = "https://github.com/ZKRoute/ZKRoute"
